### ISSUE TITLE
Don't require region string and run multiple reference sequences in parallel

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/subsamplebam#3]
It would be convenient to simply give `subsamplebam` a bam file and minimum depth without providing a region string. It would also be nice for it to handle a file with multiple reference sequences automatically. 

__Proposal:__ My pull request will include a wrapper script which can handle a BAM file with multiple reference sequences by grepping `samtools view -H `, those references & reference lengths, then creating a subsampled.bam file for each reference sequence in parallel.

**Comment by necrolyte2** [comment]
So then it would be up to the user to merge all the resulting BAMs back into a single one?
Probably best to have the wrapper script merge them all back
