### ISSUE TITLE
More representative subsampling "more-random" algorithm

### ISSUE THREAD

**Issue by averagehat** [VDBWRAIR/subsamplebam#8]
At @mmelendrez  suggestion, We may get a more representative or random subsample result by altering the "maximum overlap" #2 solution ( at the expense of some depth minimization, but probably not a lot).

When an index under the minimum depth is reached, new reads need to be picked. Instead of picking the read with the maximum overlap, randomly pick among any reads which will overlap at that index.

__Proposal__:  Add an optional flag "-r" or "--more-random" to use this "more-random" solution.

**Comment by mmelendrez** [comment]
agreed - we can compare outputs that way as well.
